splitter: token_text_splitter  #semantic_splitter
embedding: huggingface   #opnenai,huggingface, sky,dkubex
metadata:
  - default
reader:
  - file
token_text_splitter:
  chunk_size: 256
  chunk_overlap: 0
mlflow:
  experiment: huggingfaceingestion
huggingface:
  model: "BAAI/bge-large-en-v1.5"
openai:
  model: "text-embedding-ada-002"
  llmkey: ""
dkubex:
  embkey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoicHJhbGhhZC1rb2xhbWJrYXIiLCJ0eXBlIjoiYXBpIiwiaWQiOiIvZGVwbG95bWVudC9iZ2VscnNreS8ifQ.xzY1oU9ig3wNjdIT9Xp1sZ1dyKbUOpMxYCwmYor5mJY
  url: https://a591f010a8e184a7a97833e53e6642a4-1e8a9c2a4ed43993.elb.us-west-2.amazonaws.com/deployment/242/bgelrsky/
  batch_size: 10
sky:
  model: bgelrsky
  embkey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibmltZXNoLWthdGhyb3RpeWEiLCJ0eXBlIjoiYXBpIiwiaWQiOiIvZGVwbG95bWVudC9iZ2Vza3kvIn0.dPcQ1iBGgw85xWx9FYxjQ8dlJ5v1FSfy2YTsI_1c5HM
  url: http://44.193.76.252:30001/v1/
  batch_size: 10
file:
  inputs:
    loader_args:
      input_dir: /home/Ingestion_documents
      recursive: true 
      exclude_hidden: true 
      raise_on_error: true 
